image: dock0/arch
variables:
      GIT_SUBMODULE_STRATEGY: recursive

stages:
    - prepare
    - build
    - verify

.enable_sudo_nobody: &enable_sudo_nobody
        echo "nobody ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers                  # Enable sudo to work without prompting a password

############################################################################### PKGBUILD #############################################################

.pkgbuild:prepare: &pkgbuild_prepare
    stage: prepare
    variables:
        MAKE_TARGETS: prepare
    script:
        - pacman -Sy --noconfirm --needed make sed lsb-release sudo git python-pip
        - pip install gitchangelog
        - *enable_sudo_nobody
        - echo Making targets= ${MAKE_TARGETS}
        - sudo -u nobody make ${MAKE_TARGETS}
    artifacts:
        expire_in: 1 day
        paths:
            - pkgbuild/build/*

.pkgbuild:build: &pkgbuild_build
    stage: build
    script: 
        - pacman -Sy --noconfirm --needed base-devel sudo lsb-release
        - *enable_sudo_nobody
        - cd pkgbuild/build
        - sudo -u nobody makepkg --noconfirm --needed --syncdeps --force
    artifacts:
        expire_in: 1 day
        paths:
            - pkgbuild/build/PKGBUILD
            - pkgbuild/build/*.tar.xz

.pkgbuild:build-test: &pkgbuild_build_test
    stage: build
    variables:
        BUILD_DIR: build-test
    script: 
        - pacman -Sy --noconfirm --needed base-devel sudo lsb-release namcap
        - *enable_sudo_nobody
        - cd pkgbuild/$BUILD_DIR
        - sudo -u nobody makepkg --noconfirm --needed --syncdeps --force
        - namcap PKGBUILD
        - namcap *.tar.xz
    artifacts:
        expire_in: 1 day
        paths:
            - pkgbuild/$BUILD_DIR/*.tar.xz

.pkgbuild:analyze: &pkgbuild_analyze
    stage: verify
    variables:
        GIT_STRATEGY: none                          # Disable git and only rely on the artifacts
    script:
        - pacman -Sy --noconfirm --needed namcap
        - cd pkgbuild
        - namcap build/PKGBUILD
        - namcap build/*.tar.xz

.pkgbuild:verify: &pkgbuild_verify
    stage: verify
    script:
        - pacman -Sy
        - pacman --needed --noconfirm -U pkgbuild/build/*.tar.xz
        - pacman -Sy --noconfirm --needed base-devel curl gcc clang make scons clang-tools-extra cppcheck git java-environment unzip wget valgrind
        - exec-helper-integration-test
        - verification/run-examples.sh

pkgbuild:prepare:
    <<: *pkgbuild_prepare
    image: dock0/arch
    variables:
        MAKE_TARGETS: pkgbuild TARGET=prepare

arch-linux:prepare:
    <<: *pkgbuild_prepare
    image: dock0/arch
    only:
        - master

arch-linux-git:prepare:
    <<: *pkgbuild_prepare
    image: dock0/arch

pkgbuild:build:
    <<: *pkgbuild_build
    image: dock0/arch
    dependencies:
        - pkgbuild:prepare

arch-linux:build:
    <<: *pkgbuild_build
    image: dock0/arch
    dependencies:
        - arch-linux:prepare
    only:
        - master

arch-linux-git:build:
    <<: *pkgbuild_build
    image: dock0/arch
    dependencies:
        - arch-linux-git:prepare

pkgbuild:build-test:
    <<: *pkgbuild_build_test
    image: dock0/arch
    dependencies: []

pkgbuild:analyze:
    <<: *pkgbuild_analyze
    image: dock0/arch
    dependencies:
        - pkgbuild:build

arch-linux:analyze:
    <<: *pkgbuild_analyze
    image: dock0/arch
    dependencies:
        - arch-linux:build
    only:
        - master

arch-linux-git:analyze:
    <<: *pkgbuild_analyze
    image: dock0/arch
    dependencies:
        - arch-linux-git:build

pkgbuild:verify:
    <<: *pkgbuild_verify
    image: dock0/arch
    dependencies:
        - pkgbuild:build
        - pkgbuild:build-test

arch-linux:verify:
    <<: *pkgbuild_verify
    image: dock0/arch
    dependencies:
        - arch-linux:build
        - pkgbuild:build-test
    only:
        - master

arch-linux-git:verify:
    <<: *pkgbuild_verify
    image: dock0/arch
    dependencies:
        - arch-linux-git:build
        - pkgbuild:build-test

############################################################################### dpkg  #############################################################

.dpkg:prepare: &dpkg_prepare
    stage: prepare
    variables:
        MAKE_TARGETS: prepare
    script:
        - apt-get update
        - apt-get install --assume-yes sudo make sed lsb-release git gcc xz-utils python-pip
        - pip install gitchangelog mako
        - *enable_sudo_nobody
        - echo Making targets= ${MAKE_TARGETS}
        - sudo -u nobody make ${MAKE_TARGETS}
    artifacts:
        expire_in: 1 day
        paths:
            - dpkg/Makefile
            - dpkg/*.tar.xz

.dpkg:build: &dpkg_build
    stage: build
    variables:
        MAKE_TARGETS: build
        ADDITIONAL_BUILD_DEPENDENCIES: ""
    script:
        - apt-get update
        - apt-get install --assume-yes debhelper build-essential equivs devscripts sudo git lsb-release sed python-pip ${ADDITIONAL_BUILD_DEPENDENCIES}
        - pip install gitchangelog mako
        - *enable_sudo_nobody
        - echo Making targets= ${MAKE_TARGETS}
        - sudo -u nobody make ${MAKE_TARGETS}
    artifacts:
        expire_in: 1 day
        paths:
            - "dpkg/package/*"

.dpkg:build-test: &dpkg_build_test
    stage: build
    variables:
        MAKE_TARGETS: build-test
        ADDITIONAL_BUILD_DEPENDENCIES: ""
    script:
        - apt-get update
        - apt-get install --assume-yes debhelper build-essential equivs devscripts sudo git lsb-release sed python-pip ${ADDITIONAL_BUILD_DEPENDENCIES}
        - pip install gitchangelog mako
        - *enable_sudo_nobody
        - echo Making targets= ${MAKE_TARGETS}
        - sudo -u nobody make ${MAKE_TARGETS}
    artifacts:
        expire_in: 1 day
        paths:
            - "dpkg/package/*"

.dpkg:analyze: &dpkg_analyze
    stage: verify
    variables:
        LINTIAN_ARGS: "--no-cfg"
    script:
        - apt-get update
        - apt-get install --assume-yes lintian
        - cd dpkg/package
        - lintian ${LINTIAN_ARGS} --allow-root *.dsc *.changes *.deb

.dpkg:verify: &dpkg_verify
    stage: verify
    script:
        - apt-get update
        - dpkg -i dpkg/package/*.deb || true
        - apt --fix-broken --yes install
        - dpkg -i dpkg/package/*.deb
        - apt-get --yes install gcc g++ clang make scons clang-tidy cppcheck git valgrind
        - exec-helper-integration-test
        - verification/run-examples.sh

dpkg:prepare:
    <<: *dpkg_prepare
    image: debian:testing
    variables:
        MAKE_TARGETS: dpkg TARGET=prepare

debian-testing:prepare:
    <<: *dpkg_prepare
    image: debian:testing

ubuntu-xenial:prepare:
    <<: *dpkg_prepare
    image: ubuntu:xenial

ubuntu-rolling:prepare:
    <<: *dpkg_prepare
    image: ubuntu:rolling

dpkg:build:
    <<: *dpkg_build
    image: debian:testing
    dependencies:
        - dpkg:prepare
    variables:
        MAKE_TARGETS: dpkg TARGET=build

debian-testing:build:
    <<: *dpkg_build
    image: debian:testing
    dependencies:
        - debian-testing:prepare

ubuntu-xenial:build:
    variables:
        ADDITIONAL_BUILD_DEPENDENCIES: pkg-create-dbgsym
    <<: *dpkg_build
    image: ubuntu:xenial
    dependencies:
        - ubuntu-xenial:prepare

ubuntu-rolling:build:
    <<: *dpkg_build
    image: ubuntu:rolling
    dependencies:
        - ubuntu-rolling:prepare

dpkg:build-test:
    <<: *dpkg_build_test
    image: debian:testing
    dependencies: []
    variables:
        MAKE_TARGETS: dpkg TARGET=build-test

debian-testing:build-test:
    <<: *dpkg_build_test
    image: debian:testing
    dependencies: []
    variables:
        MAKE_TARGETS: dpkg TARGET=build-test

ubuntu-xenial:build-test:
    variables:
        ADDITIONAL_BUILD_DEPENDENCIES: pkg-create-dbgsym
    <<: *dpkg_build_test
    image: ubuntu:xenial
    dependencies: []

ubuntu-rolling:build-test:
    <<: *dpkg_build_test
    image: ubuntu:rolling
    dependencies: []

dpkg:analyze:
    <<: *dpkg_analyze
    image: debian:testing
    dependencies:
        - dpkg:prepare
        - dpkg:build

debian-testing:analyze:
    <<: *dpkg_analyze
    image: debian:testing
    dependencies:
        - debian-testing:prepare
        - debian-testing:build

ubuntu-xenial:analyze:
    <<: *dpkg_analyze
    image: ubuntu:xenial
    variables:
        LINTIAN_ARGS: "--fail-on-warnings"
    dependencies:
        - ubuntu-xenial:prepare
        - ubuntu-xenial:build

ubuntu-rolling:analyze:
    <<: *dpkg_analyze
    image: ubuntu:rolling
    dependencies:
        - ubuntu-rolling:prepare
        - ubuntu-rolling:build

dpkg:verify:
    <<: *dpkg_verify
    image: debian:testing
    dependencies:
        - dpkg:build
        - dpkg:build-test

debian-testing:verify:
    <<: *dpkg_verify
    image: debian:testing
    dependencies:
        - debian-testing:build
        - debian-testing:build-test

ubuntu-xenial:verify:
    <<: *dpkg_verify
    image: ubuntu:xenial
    dependencies:
        - ubuntu-xenial:build
        - ubuntu-xenial:build-test

ubuntu-rolling:verify:
    <<: *dpkg_verify
    image: ubuntu:rolling
    dependencies:
        - ubuntu-rolling:build
        - ubuntu-rolling:build-test
