image: dock0/arch

before_script:
    - pacman -Sy --noconfirm

stages:
    - build
    - analyze
    - verify

pkgbuild:build:
    stage: build
    script: 
        - pacman -S --noconfirm --needed base-devel make
        - echo "nobody ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers                  # Enable sudo to work without prompting a password
        - make pkgbuild
    artifacts:
        expire_in: 1 day
        paths:
            - pkgbuild/*.tar.xz

pkgbuild:analyze:
    stage: analyze
    dependencies:
        - pkgbuild:build
    script:
        - pacman -S --noconfirm --needed namcap
        - cd pkgbuild
        - namcap PKGBUILD
        - namcap *.tar.xz

pkgbuild:verify:
    stage: verify
    dependencies:
        - pkgbuild:build
    script:
        - pacman --needed --noconfirm -U pkgbuild/*.tar.xz
        - git submodule update --init
        - exec-helper --settings-file exec-helper/src/plugins/examples/command-line-command.example example

dpkg:build:
    image: ubuntu:xenial
    stage: build
    script:
        - apt-get update
        - apt-get install --assume-yes debhelper build-essential
        - make ubuntu
    artifacts:
        expire_in: 1 day
        paths:
            - ../*.dsc
            - ../*.tar.*
            - ../*.changes
            - ../*.deb

dpkg:analyze:
    stage: analyze
    dependencies:
        - dpkg: build
    script:
        - apt-get update
        - apt-get install --assume-yes lintian
        - lintian
