image: dock0/arch
variables:
      GIT_SUBMODULE_STRATEGY: recursive

stages:
    - prepare
    - build
    - analyze
    - verify

.pkgbuild:prepare: &pkgbuild_prepare
    script:
        - pacman -Sy --noconfirm --needed make sed lsb-release sudo
        - echo "nobody ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers                  # Enable sudo to work without prompting a password
        - echo Making targets= ${MAKE_TARGETS}
        - sudo -u nobody make ${MAKE_TARGETS}
    artifacts:
        expire_in: 1 day
        paths:
            - pkgbuild/build/*

.pkgbuild:build: &pkgbuild_build
    script: 
        - pacman -Sy --noconfirm --needed base-devel lsb-release sudo
        - echo "nobody ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers                  # Enable sudo to work without prompting a password
        - cd pkgbuild/build
        - sudo -u nobody makepkg --noconfirm --needed --syncdeps --force
    artifacts:
        expire_in: 1 day
        paths:
            - pkgbuild/build/PKGBUILD
            - pkgbuild/build/*.tar.xz

.pkgbuild:analyze: &pkgbuild_analyze
    variables:
        GIT_STRATEGY: none                          # Disable git and only rely on the artifacts
    script:
        - pacman -Sy --noconfirm --needed namcap
        - cd pkgbuild
        - namcap build/PKGBUILD
        - namcap build/*.tar.xz

.pkgbuild:verify: &pkgbuild_verify
    variables:
        GIT_STRATEGY: none                          # Disable git and only rely on the artifacts
    script:
        - pacman --needed --noconfirm -U pkgbuild/build/*.tar.xz
        - pacman -Sy --noconfirm --needed base-devel curl gcc clang make scons clang-tools-extra cppcheck git java-environment unzip wget valgrind
        - verification/run-examples.sh

pkgbuild:prepare:
    stage: prepare
    variables:
        MAKE_TARGETS: prepare
    <<: *pkgbuild_prepare

arch-linux:prepare:
    stage: prepare
    variables:
        MAKE_TARGETS: arch TARGET=prepare
    only:
        - master
    <<: *pkgbuild_prepare

arch-linux-git:prepare:
    stage: prepare
    variables:
        MAKE_TARGETS: arch TARGET=prepare-git
    <<: *pkgbuild_prepare

pkgbuild:build:
    stage: build
    dependencies:
        - pkgbuild:prepare
    <<: *pkgbuild_build

arch-linux:build:
    stage: build
    dependencies:
        - arch-linux:prepare
    only:
        - master
    <<: *pkgbuild_build

arch-linux-git:build:
    stage: build
    dependencies:
        - arch-linux-git:prepare
    <<: *pkgbuild_build

pkgbuild:analyze:
    stage: analyze
    dependencies:
        - pkgbuild:build
    <<: *pkgbuild_analyze

arch-linux:analyze:
    stage: analyze
    dependencies:
        - arch-linux:build
    only:
        - master
    <<: *pkgbuild_analyze

arch-linux-git:analyze:
    stage: analyze
    dependencies:
        - arch-linux-git:build
    <<: *pkgbuild_analyze

pkgbuild:verify:
    stage: verify
    dependencies:
        - pkgbuild:build
    <<: *pkgbuild_verify

arch-linux:verify:
    stage: verify
    dependencies:
        - arch-linux:build
    only:
        - master
    <<: *pkgbuild_verify

arch-linux-git:verify:
    stage: verify
    dependencies:
        - arch-linux-git:build
    <<: *pkgbuild_verify

dpkg:build:
    image: debian:testing
    stage: build
    script:
        - apt-get update
        - apt-get install --assume-yes debhelper build-essential equivs devscripts sudo
        - echo "nobody ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers                  # Enable sudo to work without prompting a password
        - sudo -u nobody make dpkg
    artifacts:
        expire_in: 1 day
        paths:
            - "*.dsc"
            - "*.tar.*"
            - "*.changes"
            - "*.deb"
            - "*.buildinfo"

dpkg:analyze:
    image: debian:testing
    stage: analyze
    dependencies:
        - dpkg:build
    script:
        - apt-get update
        - apt-get install --assume-yes lintian
        - cd dpkg && lintian --fail-on-warnings

debian-testing:build:
    image: debian:testing
    stage: build
    script:
        - apt-get update
        - apt-get install --assume-yes debhelper build-essential equivs devscripts sudo lsb-release
        - echo "nobody ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers                  # Enable sudo to work without prompting a password
        - sudo -u nobody make
    artifacts:
        expire_in: 1 day
        paths:
            - "*.dsc"
            - "*.tar.*"
            - "*.changes"
            - "*.deb"
            - "*.buildinfo"

debian-testing:analyze:
    image: debian:testing
    stage: analyze
    dependencies:
        - debian-testing:build
    script:
        - apt-get update
        - apt-get install --assume-yes lintian
        - cd dpkg && lintian --fail-on-warnings

ubuntu-xenial:build:
    image: ubuntu:xenial
    stage: build
    script:
        - apt-get update
        - apt-get install --assume-yes debhelper build-essential equivs devscripts sudo lsb-release
        - echo "nobody ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers                  # Enable sudo to work without prompting a password
        - sudo -u nobody make
    artifacts:
        expire_in: 1 day
        paths:
            - "*.dsc"
            - "*.tar.*"
            - "*.changes"
            - "*.deb"

ubuntu-xenial:analyze:
    image: ubuntu:xenial
    stage: analyze
    dependencies:
        - ubuntu-xenial:build
    script:
        - apt-get update
        - apt-get install --assume-yes lintian
        - cd dpkg && lintian --fail-on-warnings

