image: dock0/arch

before_script:
    - pacman -Sy --noconfirm
    - pacman -S --noconfirm base-devel

stages:
    - build
    - test
    - verify

pkgbuild:build:
    stage: build
    script: 
        - cd pkgbuild
        - makepkg -s
    artifacts:
        expire_in: 1 day
        paths:
            - pkgbuild/*.tar.xz

pkgbuild:test:
    stage: test
    dependencies:
        - pkgbuild:build
    script:
        - pacman -S --noconfirm --needed namcap
        - cd pkgbuild
        - namcap PKGBUILD
        - namcap *.tar.xz

pkgbuild:verify:
    stage: verify
    dependencies:
        - pkgbuild:build
    script:
        - pacman -U pkgbuild/*.tar.gz
        - git submodules update --init
        - exec-helper --settings-file exec-helper/src/plugins/examples/command-line-command.example example
